### PR TITLE
Fix some problems with loading via webclient

### PR DESCRIPTION
**Pull request by Multiball**
I realized that the blank cases in the switch statement were leading to writing an extra blank character when no action should have been taken. Now that we have continue statements, ignoring the character is ignoring the character.

### CODE REVIEW

**Comment by Multiball** [comment]
@gartonrd 
You mentioned "watchdog timeouts." What is a watchdog timeout, and how do I avoid it?

**Comment by gartonrd** [comment]
Embedded systems often have a piece of hardware called a watchdog timer. The software must write to the watchdog timer before it times out, or the processor will be reset (as if powered down and back up again - ie. program execution starts over from the beginning). This is a safety mechanism to recover if the software gets hung up. 
The workings of the watchdog timer in the ESP-8266 are somewhat obscure, since it is handled by the operating system which is not well documented. If you bring up the arduino monitor, you can see when it times out because a message is printed along with a bunch of garbage (the contents of the stack register, which are not too useful).
To avoid watchdog timeouts, your software must yield to the operating system so it has a chance to stroke the watchdog timer. This is done by executing a Delay() instruction. One solution is to add a Delay(1) to your code in time-consuming loops. Another solution is to  take advantage of the Delay(5) which is executed every time 30 bytes are written to the EEPROM. (I would choose the latter, but it is a little more complicated) Either way, it needs to be fixed. I can fix it if you want me to, but I would rather that you do it.

**Comment by gartonrd** [comment]
I am not convinced the continue statements will fix the problem. Looking at your code in more detail, I think the problem is with that if statement after the cases in the switch statement and before the close brace of the for statement. The whitespace characters need to skip that if statement. Maybe you need a "whitespace" variable that gets set in the whitespace cases and checked in the if statement. I don't use the continue statement when I code, so I am not sure exactly what it will do. If it exits the switch statement, that won't solve the problem. If it exits the for loop, that won't solve the problem either. Take a closer look, and please test. I do not want to be your bug finder.

**Comment by gartonrd** [comment]
I looked up the continue statement, and maybe it does fix the problem. What I found is that it will jump to the end of the for statement, but does not exit the for statement. If this is the case, it looks like it will work

**Comment by Multiball** [comment]
Well, it worked in my tests.
Have you never used the `continue` statement before?

**Comment by Multiball** [comment]
I've made some changes so that we're not sending 100 requests to the ESP every second. That may have been bogging things down. Now, we send only one request per second.
In an effort not to lose too much information between requests, we now get the ten most recent records, not just the last one. Let me know if this fixes the problem.

I can't rightly test the fix because I've never observed a timeout myself, as far as I can tell. With the current code, I can consistently upload a large pattern (21489 bytes raw, 10466 bytes after conversion) without triggering a timeout, so it _seems_ like it ought to work.

If the problem persists, let me know what exactly causes the timeout. Does it time out in the course of normal execution? Does it time out when loading a new pattern? When uploading a _specific_ pattern? What sort of console output do you see immediately before the timeout? Can you tell if the timeout always happens at a the same point in execution, or a different one every time?

**Comment by Multiball** [comment]
Merging based on contentment with results last night. If this assumption is in error, then we can always roll this change back.

**Comment by gartonrd** [comment]
Yes, I was very happy with how this branch worked. I agree with merging.

**Pull request merged**
