### PR TITLE
Removed comments that appeared redundant.

### PR DESCRIPTION
**Pull request by Multiball**
@gartonrd , how's it look?

### CODE REVIEW

**Comment by gartonrd** [comment]
I edited the headers of all of the files and pushed them. I think we should wait to merge until after the logon branch and the webclient-fixes branch have been merged. I am envisioning that these two branches, since they are based the before changes of this branch, will try to undo what this branch is doing. Maybe we should also not create any new branches until this (and the other two) have been merged. But I am a novice, and you are the expert. Maybe you know a way around this problem. Please advise.

**Comment by gartonrd** [comment]
I could not navigate to this branch on my PC, probably because it was created after I did the clone. So I did a new clone, and then I could get there. But I think this may not be the best way to operate. There is probably a way to upgrade my existing repo with the new branch. So I went back to my old clone, and tried "git pull origin remove-comments". The new branch was not created. I think the files from this branch just got dumped into the master branch, where I was currently pointing. So, should have instead used this commmand "git checkout -b remove-comments", which I think would create the branch and pull the files? And after the branch exists should I the use the command "git pull origin remove-comments" to update it if changes get made? Is the word origin necessary here?

**Comment by Multiball** [comment]
You should never have to clone a repo more than once. The way to get the list of branches available on the remote repository is to run `$git pull` to fetch the latest changes from your current branch. `$git pull` will not switch you to a new branch; you must `$git pull` the branch you're currently in. If git complains about not having an upstream, then run `$git pull origin <branch name>`. Then, you should be able to `$git checkout remove-comments`. The `-b` argument to `git checkout` specifies that you want to create a new branch. If you try to create a new branch whose name matches an existing branch, git should throw an error.

Things to note:
- `$git pull` (among other things) pulls the list of branches that are on the remote.
- `$git checkout <branch name>` is the command used to switch between branches: this command is used both for branches existing on the local repository and for switching to a branch that exists only on the remote repository.
- `$git checkout -b <branch name>` is used to create a new branch with <branch name>.

We should be able to create branches as we please; we have only to make sure that they don't clobber anything and are up-to-date with the latest version of master before we do. The way I am most familiar with of doing this is the `rebase` command: https://git-scm.com/book/en/v2/Git-Branching-Rebasing . The crux of the matter is pulling the latest version of master, then switching to the branch and running `$git rebase master`. If merge conflicts arise, they can be resolved as necessary. The bottom line is that we should never hold up creation or merge of a branch for fear of conflicts.

**Comment by gartonrd** [comment]
Clearly, I still have some learning to do. I had not found the "git book"  that you provided the link to. I am going to read this whole thing.

I think the rebase command is what I need to get my logon branch up to date. After I educate myself a little more, I will probably call you for some help. The "git book" says you should not use the rebase command on a branch that you have made public, which is the case for logon. So I will want to consult with you and make sure I don't really screw things up.

**Comment by gartonrd** [comment]
I have spent the last several days studying the "git book'. I now know a lot more than I used to, and am ready to get back to the real work. I should have the logon branch fixed tomorrow.

**Pull request merged**
