### PR TITLE
Added web-based uploading of flake files.

### PR DESCRIPTION
**Pull request by Multiball**
To use the client, note the IP address printed to the inspector upon startup. Copy-paste that IP address into a web browser. The interface should be fairly self-explanitory.

At this point, the code expects the file to be uploaded to be a valid fl5; a file containing binary records as documented in the specification. Whether or not this is the ultimately desired state of things remains to be determined.

### CODE REVIEW

**Comment by Multiball** [comment]
Any comments here? Should this code get merged?

**Comment by gartonrd** [comment]
I know you will have to modify this code because the file your dad will give you will be in ASCII Hex, not binary. What is the best way to proceed? Go ahead and merge, then make the modification; or scrap this branch and make a new one with the ASCII Hex modification? Go whichever route you prefer. I am waiting for the ASCII Hex version before I do any testing.

**Comment by Multiball** [comment]
I can just modify this branch to include the ASCII hex feature. It shouldn't be too hard to implement. I'll try to get it up some time tomorrow.

**Comment by Multiball** [comment]
Uploaded files are now expected to be in ASCII hex.
Lines beginning with '#' are treated as comments.

**Comment by gartonrd** [comment]
Before merging, could you:
1. bump up the version number - at top of A0_ESP
2. move you strings for ssid and password to top of A0_ESP, just under version number

**Comment by Multiball** [comment]
I've made the requested changes.

Besides that, everything is good? Style is appropriate? File naming is acceptable? No glaring omissions or inefficiencies, or potential conflicts with other parts of the code or probably future development?

**Comment by gartonrd** [comment]
I wasn't going to get nit picky, but since you asked, I would prefer A0_WebServer to be named A3_WebServer. And I like to put my open brackets on a separate line, but there are a lot of them and it is OK if you don't change this. If you could change the file name, I think you could go ahead and merge.

**Comment by Multiball** [comment]
I have renamed the file, and adjusted the brackets. There weren't /that/ many of them; using the "find" feature made it easy.

When multiple people are working on the same code, consistent style and naming conventions are important. If you see anything else that doesn't match the rest of the project, don't hesitate to mention it.

**Comment by gartonrd** [comment]
Now you are really asking for it. You could put a header in A3_WebServer like is in the first few lines of A0_ESP. Also, move your break statements to the left so they are indented the same as your case statements. Not wrong, but to follow the style I have been using.

**Comment by Multiball** [comment]
Does this look correct? Is there anything else that should be changed?

**Comment by gartonrd** [comment]
It has taken on a beautiful look, at least to my eye. Can you merge, or do I have to?

**Pull request merged**
